services:
  - type: static_site
    name: note-app-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://note-app-backend.onrender.com/api
        scope: build
    routes:
      - path: /
        destination: /
      - path: /*
        destination: /index.html
