services:
  - type: web
    name: note-app-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongo_url
        scope: secret
      - key: FRONTEND_URL
        scope: secret
    healthCheckPath: /health
    routes:
      - path: /api
        destination: /api
